[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "icecream>=2.1.8",
    "matplotlib>=3.10.8",
    "pandas>=2.3.3",
    "playwright>=1.57.0",
    "pydantic>=2.12.5",
    "python-calamine>=0.6.1",
    "xlsxwriter>=3.2.9",
]
